### PR TITLE
Drop down menus

### PR DESCRIPTION
**Pull request by Oozaru71**
This first request completes the first 3 tasks of the given issue.

### CODE REVIEW

**Comment by Oozaru71** [comment]
Regarding point 2: Currently the way the application is set up when the app searches for the views it goes "../Views/Home/..." or "..Views/Shared/..." hence why all the cshtml have been placed only under home. The app only searches for folders inside views called home or shared. While this could certainly be changed, it seems easier to simply add the views under home and organize them under folders there.

**Comment by Oozaru71** [comment]
Any ideas for notification page functionality?

**Comment by Alejandro-HUB** [comment]
@Oozaru71 Wow you actually knocked it out right outta the park! Your changes look amazing, great job using the assets from the template haha. I really like how you implemented the tab at the top of the help page and the settings page.

I think after these few things you will be finished with this task 💯 

**Notifications Page**

 We currently show notifications like this:

image

For the notification page, I'm thinking we do an amplified version of the above as a panel with a scroll bar that shows a list of notifications. 
You can do a panel that shows notifications just like the one above but on a bigger scale, like larger rectangles.

Maybe something like this but like taking up the whole page:
image

You already have the existing notifications drop-down that shows when you click the bell as a base.

_Types of notifications as placeholders (for now):_
I'm thinking that when a new Hot Pick song comes out or something we show a notification about it. Or if we do implement the chatting option in the future. It says "Sophi sent you an email" but you can change it to "message" instead of email.

Let me know your thoughts.

**Profile Picture:**
If you don't mind, since you're already in the process. Could you make the profile picture on the profile page circular and not an oval? Perhaps remove the dotted line (pixeled) border as well. The size looks great, but the oval and border look strange:

image

**About Tab in Help Page**
Perhaps you can do something similar to what you did on the Contact Us page where the bold is the title and the below is the text:

image

It currently looks like this:
image

You could make it the same font and size as the "Contact Us" page with a title that says "About Alody" in bold.

**Comment by Oozaru71** [comment]
@Alejandro-HUB  This should be the final commit for this set of task as it now points to a notification tab correctly. Notification is obviously still not dynamic (I have some ideas as to how to implement this) and I got lazy with the place holders; however, this should meet the requirements for now.

**Comment by Alejandro-HUB** [comment]
@Oozaru71 Excellent work, all the work items for this task were successfully completed! I will merge your branch now and tomorrow I will give you your next set of tasks.

**Pull request merged**
